insert into payments (id, booking_id, method, amount, status) values (1, 1, 'net banking', 1535.01, 'pending');
insert into payments (id, booking_id, method, amount, status) values (3, 3, 'net banking', 2933.75, 'success');
insert into payments (id, booking_id, method, amount, status) values (4, 4, 'net banking', 1534.47, 'success');
insert into payments (id, booking_id, method, amount, status) values (5, 5, 'upi', 2510.44, 'success');
insert into payments (id, booking_id, method, amount, status) values (6, 6, 'cash', 1632.74, 'success');
insert into payments (id, booking_id, method, amount, status) values (7, 7, 'card', 1051.32, 'success');
insert into payments (id, booking_id, method, amount, status) values (8, 8, 'card', 1995.3, 'pending');
insert into payments (id, booking_id, method, amount, status) values (9, 9, 'card', 1732.35, 'success');
insert into payments (id, booking_id, method, amount, status) values (10, 10, 'net banking', 1866.13, 'success');
insert into payments (id, booking_id, method, amount, status) values (11, 11, 'upi', 1552.91, 'success');
insert into payments (id, booking_id, method, amount, status) values (12, 12, 'card', 2493.04, 'success');
insert into payments (id, booking_id, method, amount, status) values (14, 14, 'card', 2529.32, 'pending');
insert into payments (id, booking_id, method, amount, status) values (15, 15, 'net banking', 2192.83, 'success');
insert into payments (id, booking_id, method, amount, status) values (16, 16, 'net banking', 2478.55, 'success');
insert into payments (id, booking_id, method, amount, status) values (17, 17, 'upi', 2188.6, 'success');
insert into payments (id, booking_id, method, amount, status) values (18, 18, 'net banking', 1914.34, 'success');
insert into payments (id, booking_id, method, amount, status) values (19, 19, 'card', 1854.4, 'success');
insert into payments (id, booking_id, method, amount, status) values (20, 20, 'net banking', 2876.08, 'success');
insert into payments (id, booking_id, method, amount, status) values (22, 22, 'net banking', 2860.63, 'success');
insert into payments (id, booking_id, method, amount, status) values (23, 23, 'card', 1010.09, 'success');
insert into payments (id, booking_id, method, amount, status) values (24, 24, 'upi', 1197.6, 'success');
insert into payments (id, booking_id, method, amount, status) values (25, 25, 'upi', 2367.05, 'success');
insert into payments (id, booking_id, method, amount, status) values (26, 26, 'cash', 1851.7, 'success');
insert into payments (id, booking_id, method, amount, status) values (27, 27, 'cash', 1962.23, 'success');
insert into payments (id, booking_id, method, amount, status) values (28, 28, 'card', 2259.62, 'success');
insert into payments (id, booking_id, method, amount, status) values (29, 29, 'upi', 2891.94, 'success');
insert into payments (id, booking_id, method, amount, status) values (32, 32, 'upi', 1373.88, 'success');
insert into payments (id, booking_id, method, amount, status) values (33, 33, 'upi', 1774.45, 'success');
insert into payments (id, booking_id, method, amount, status) values (34, 34, 'net banking', 2505.46, 'success');
insert into payments (id, booking_id, method, amount, status) values (35, 35, 'net banking', 1650.92, 'success');
insert into payments (id, booking_id, method, amount, status) values (36, 36, 'net banking', 1836.68, 'success');
insert into payments (id, booking_id, method, amount, status) values (37, 37, 'net banking', 2898.81, 'success');
insert into payments (id, booking_id, method, amount, status) values (38, 38, 'net banking', 1971.79, 'success');
insert into payments (id, booking_id, method, amount, status) values (40, 40, 'net banking', 2791.24, 'success');
insert into payments (id, booking_id, method, amount, status) values (42, 42, 'net banking', 1666.57, 'success');
insert into payments (id, booking_id, method, amount, status) values (43, 43, 'upi', 1279.1, 'success');
insert into payments (id, booking_id, method, amount, status) values (44, 44, 'net banking', 1110.64, 'success');
insert into payments (id, booking_id, method, amount, status) values (45, 45, 'net banking', 2446.0, 'success');
insert into payments (id, booking_id, method, amount, status) values (46, 46, 'upi', 2142.52, 'success');
insert into payments (id, booking_id, method, amount, status) values (47, 47, 'card', 2411.14, 'success');
insert into payments (id, booking_id, method, amount, status) values (48, 48, 'cash', 1710.6, 'pending');
insert into payments (id, booking_id, method, amount, status) values (50, 50, 'upi', 1028.94, 'success');
