insert into ratings (id, booking_id, value, feedback) values (5, 5, 2, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into ratings (id, booking_id, value, feedback) values (7, 7, 5, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into ratings (id, booking_id, value, feedback) values (10, 10, 5, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into ratings (id, booking_id, value, feedback) values (15, 15, 2, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into ratings (id, booking_id, value, feedback) values (17, 17, 5, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into ratings (id, booking_id, value, feedback) values (19, 19, 1, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into ratings (id, booking_id, value, feedback) values (20, 20, 5, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into ratings (id, booking_id, value, feedback) values (23, 23, 4, 'Integer non velit.');
insert into ratings (id, booking_id, value, feedback) values (24, 24, 5, 'Nulla tellus.');
insert into ratings (id, booking_id, value, feedback) values (26, 26, 1, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into ratings (id, booking_id, value, feedback) values (27, 27, 5, 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into ratings (id, booking_id, value, feedback) values (28, 28, 5, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into ratings (id, booking_id, value, feedback) values (29, 29, 4, 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.');
insert into ratings (id, booking_id, value, feedback) values (32, 32, 2, 'Suspendisse potenti.');
insert into ratings (id, booking_id, value, feedback) values (35, 35, 4, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into ratings (id, booking_id, value, feedback) values (36, 36, 2, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into ratings (id, booking_id, value, feedback) values (38, 38, 1, 'Nunc purus. Phasellus in felis.');
insert into ratings (id, booking_id, value, feedback) values (42, 42, 1, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into ratings (id, booking_id, value, feedback) values (44, 44, 4, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into ratings (id, booking_id, value, feedback) values (45, 45, 1, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into ratings (id, booking_id, value, feedback) values (47, 47, 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into ratings (id, booking_id, value, feedback) values (50, 50, 4, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
